/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paugi
 */
public class GestorEmpleados extends javax.swing.JInternalFrame {
    Controlador c;
    DefaultTableModel dtm;
    
    /**
     * Creates new form GestorVentas
     */
    public GestorEmpleados(Controlador c, int indicePanel) {
        initComponents();
        this.c = c; 
        if (indicePanel == 0) {
            jTabbedPane1.setSelectedIndex(0);
            jTabbedPane1.setEnabledAt(1, false);
            jTabbedPane1.setEnabledAt(0, true);
        } else {
            jTabbedPane1.setSelectedIndex(1);
            jTabbedPane1.setEnabledAt(0, false);
            jTabbedPane1.setEnabledAt(1, true);
        }
  
        IniciarTablaEmpleados();
        c.CargarTablaEmpleados(dtm);
    }
    
    private void IniciarTablaEmpleados() {
        dtm = new DefaultTableModel();
        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new String[] {"NIF", "Nombre", "Apellidos", "DNI"} );
    }
    
    private void ModoRegistrarEmpleado() {
        jTextFieldNifEmpleado.setText("");
        jTextFieldDniEmpleado.setText("");
        jTextFieldNombreEmpleado.setText("");
        jTextFieldApellidosEmpleado.setText("");
        
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(0, false);
    }
    
    private void VolverALista() {
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelListarEmpleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonModoRegistrarEmpleado = new javax.swing.JButton();
        jPanelRegistrarEmpleado = new javax.swing.JPanel();
        jTextFieldNifEmpleado = new javax.swing.JTextField();
        jTextFieldDniEmpleado = new javax.swing.JTextField();
        jTextFieldNombreEmpleado = new javax.swing.JTextField();
        jTextFieldApellidosEmpleado = new javax.swing.JTextField();
        jLabelNifEmpleado = new javax.swing.JLabel();
        jLabelDniEmpleado = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jButtonRegistrarEmpleado = new javax.swing.JButton();
        jButtonVolverALista = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestor Empleados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonModoRegistrarEmpleado.setText("Registrar nuevo empleado -->");
        jButtonModoRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoRegistrarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarEmpleadosLayout = new javax.swing.GroupLayout(jPanelListarEmpleados);
        jPanelListarEmpleados.setLayout(jPanelListarEmpleadosLayout);
        jPanelListarEmpleadosLayout.setHorizontalGroup(
            jPanelListarEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarEmpleadosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonModoRegistrarEmpleado))
        );
        jPanelListarEmpleadosLayout.setVerticalGroup(
            jPanelListarEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonModoRegistrarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar", jPanelListarEmpleados);

        jTextFieldDniEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniEmpleadoActionPerformed(evt);
            }
        });

        jTextFieldNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreEmpleadoActionPerformed(evt);
            }
        });

        jLabelNifEmpleado.setText("NIF:");

        jLabelDniEmpleado.setText("DNI:");

        jLabelNombre.setText("Nombre:");

        jLabelApellidos.setText("Apellidos:");

        jButtonRegistrarEmpleado.setText("Registrar");
        jButtonRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarEmpleadoActionPerformed(evt);
            }
        });

        jButtonVolverALista.setText("<-- Volver a lista");
        jButtonVolverALista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAListaActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelRegistrarEmpleadoLayout = new javax.swing.GroupLayout(jPanelRegistrarEmpleado);
        jPanelRegistrarEmpleado.setLayout(jPanelRegistrarEmpleadoLayout);
        jPanelRegistrarEmpleadoLayout.setHorizontalGroup(
            jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelRegistrarEmpleadoLayout.createSequentialGroup()
                        .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRegistrarEmpleadoLayout.createSequentialGroup()
                                .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNifEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(jLabelNifEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDniEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDniEmpleado)))
                            .addComponent(jButtonVolverALista))
                        .addGap(1, 1, 1))
                    .addGroup(jPanelRegistrarEmpleadoLayout.createSequentialGroup()
                        .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreEmpleado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldApellidosEmpleado)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarEmpleadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelRegistrarEmpleadoLayout.setVerticalGroup(
            jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolverALista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNifEmpleado)
                    .addComponent(jLabelDniEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDniEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNifEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonRegistrarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Anyadir", jPanelRegistrarEmpleado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreEmpleadoActionPerformed

    private void jTextFieldDniEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniEmpleadoActionPerformed

    private void jButtonRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarEmpleadoActionPerformed
        String nif = jTextFieldNifEmpleado.getText();
        String nombre = jTextFieldNombreEmpleado.getText();
        String apellidos = jTextFieldApellidosEmpleado.getText();
        String dni = jTextFieldDniEmpleado.getText();
        
        if (nif.length() > 0 && nombre.length() > 0 && apellidos.length() > 0 && dni.length() > 0) {
            IniciarTablaEmpleados();
            c.IntroducirEnTablaEmpleados(nif, nombre, apellidos, dni, dtm);
        } else {
            jLabelError.setText("Faltan campos por rellenar.");
        }              
    }//GEN-LAST:event_jButtonRegistrarEmpleadoActionPerformed

    private void jButtonModoRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoRegistrarEmpleadoActionPerformed
        ModoRegistrarEmpleado();
    }//GEN-LAST:event_jButtonModoRegistrarEmpleadoActionPerformed

    private void jButtonVolverAListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAListaActionPerformed
        VolverALista();
    }//GEN-LAST:event_jButtonVolverAListaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModoRegistrarEmpleado;
    private javax.swing.JButton jButtonRegistrarEmpleado;
    private javax.swing.JButton jButtonVolverALista;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDniEmpleado;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelNifEmpleado;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanelListarEmpleados;
    private javax.swing.JPanel jPanelRegistrarEmpleado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldApellidosEmpleado;
    private javax.swing.JTextField jTextFieldDniEmpleado;
    private javax.swing.JTextField jTextFieldNifEmpleado;
    private javax.swing.JTextField jTextFieldNombreEmpleado;
    // End of variables declaration//GEN-END:variables
}