/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paugi
 */
public class GestorVentas extends javax.swing.JInternalFrame {
    Controlador c;
    DefaultTableModel dtm;
    boolean nuevoCliente;
    DefaultComboBoxModel<String> dcbmNif;
    DefaultComboBoxModel<String> dcbmDni;
    
    /**
     * Creates new form GestorVentas
     */
    public GestorVentas(Controlador c, int indicePaneGestorCompras) {
        initComponents();
        this.c = c; 
        
        jTabbedPaneClienteVenta.setSelectedIndex(0);
        jTabbedPaneClienteVenta.setEnabledAt(1, false);
        jTabbedPaneClienteVenta.setEnabledAt(0, true);
        
        if (indicePaneGestorCompras == 0) {
            jTabbedPaneGestorVentas.setSelectedIndex(0);
            jTabbedPaneGestorVentas.setEnabledAt(1, false);
            jTabbedPaneGestorVentas.setEnabledAt(0, true);
        } else {
            jTabbedPaneGestorVentas.setSelectedIndex(1);
            jTabbedPaneGestorVentas.setEnabledAt(1, true);
            jTabbedPaneGestorVentas.setEnabledAt(0, false);
        }
  
        IniciarTablaVentas();
        c.CargarTablaVentas(dtm);
        IniciarComboboxNif();
        c.CargarComboboxNif(dcbmNif);
        IniciarComboboxDni();
        c.CargarComboboxDni(dcbmDni);
        
        nuevoCliente = false;
    }
    
    private void IniciarTablaVentas() {
        dtm = new DefaultTableModel();
        jTableVentas.setModel(dtm);
        dtm.setColumnIdentifiers(new String[] {"Empleado", "Cliente", "Coche", "Fecha"} );
    }
    
    private void IniciarComboboxNif() {
        dcbmNif = new DefaultComboBoxModel<String>();
        jComboBoxNifEmpleadoVenta.setModel(dcbmNif);
    }
    
    private void IniciarComboboxDni() {
        dcbmDni = new DefaultComboBoxModel<String>();
        jComboBoxDniClienteExistente.setModel(dcbmDni);
    }
    
    private void IniciarDatosEmpleado(String nif) {
        String nombre = c.CargarNombreEmpleado(nif);
        String apellidos = c.CargarApellidosEmpleado(nif);
        String dni = c.CargarDniEmpleado(nif);
        
        jLabelNombreEmpleadoVenta.setText(nombre);
        jLabelApellidosEmpleadoVenta.setText(apellidos);
        jLabelDniEmpleadoVenta.setText(dni);
    }
    
    private void IniciarDatosCliente(String dni) {
        String nombre = c.CargarNombreCliente(dni);
        String apellidos = c.CargarApellidosCliente(dni);
        
        jLabelNombreClienteExistente.setText(nombre);
        jLabelApellidosClienteExistente.setText(apellidos);
    }
    
    private void IniciarDatosCoche(Long id) {
        String marca = c.CargarMarcaCocheConcesionarioDisponible(id);
        String modelo = c.CargarModeloCocheConcesionarioDisponible(id);
        String anyo = c.CargarAnyoCocheConcesionarioDisponible(id);
        String color = c.CargarColorCocheConcesionarioDisponible(id);
        String kilometraje = c.CargarKilometrajeCocheConcesionarioDisponible(id);
        String precio = c.CargarPrecioCocheConcesionarioDisponible(id);
        
        jLabelMarcaCocheVenta.setText(marca);
        jLabelModeloCocheVenta.setText(modelo);
        jLabelAnyoCocheVenta.setText(anyo);
        jLabelColorCocheVenta.setText(color);
        jLabelKilometrajeCocheVenta.setText(kilometraje);
        jLabelPrecioCocheVenta.setText(precio);
        
        
    }
    
    private void ModoRegistrarVenta() {
        jTabbedPaneGestorVentas.setSelectedIndex(1);
        jTabbedPaneGestorVentas.setEnabledAt(1, true);
        jTabbedPaneGestorVentas.setEnabledAt(0, false);
    }
    
    private void VolverALista() {
        jTabbedPaneGestorVentas.setSelectedIndex(0);
        jTabbedPaneGestorVentas.setEnabledAt(0, true);
        jTabbedPaneGestorVentas.setEnabledAt(1, false);
    }
    
    private void UsarClienteNuevo() {
        nuevoCliente = true;
        jTabbedPaneClienteVenta.setSelectedIndex(1);
        jTabbedPaneClienteVenta.setEnabledAt(1, true);
        jTabbedPaneClienteVenta.setEnabledAt(0, false);
    }
    
    private void UsarClienteExistente() {
        nuevoCliente = false;
        jTabbedPaneClienteVenta.setSelectedIndex(0);
        jTabbedPaneClienteVenta.setEnabledAt(0, true);
        jTabbedPaneClienteVenta.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneGestorVentas = new javax.swing.JTabbedPane();
        jPanelListarVentas = new javax.swing.JPanel();
        jScrollPaneGestorVentas = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jButtonModoRegistrarVenta = new javax.swing.JButton();
        jPanelRegistrarVentas = new javax.swing.JPanel();
        jPanelClienteVenta = new javax.swing.JPanel();
        jTabbedPaneClienteVenta = new javax.swing.JTabbedPane();
        jPanelClienteExistenteVenta = new javax.swing.JPanel();
        jComboBoxDniClienteExistente = new javax.swing.JComboBox<>();
        jLabelEtiquetaNombreClienteExistente = new javax.swing.JLabel();
        jLabelEtiquetaApellidosNombreClienteExistente = new javax.swing.JLabel();
        jLabelEtiquetaDniClienteExistente = new javax.swing.JLabel();
        jLabelNombreClienteExistente = new javax.swing.JLabel();
        jLabelApellidosClienteExistente = new javax.swing.JLabel();
        jButtonUsarClienteNuevo = new javax.swing.JButton();
        jPanelNuevoClienteVenta = new javax.swing.JPanel();
        jLabelEtiquetaDniNuevoClienteVenta = new javax.swing.JLabel();
        jLabelEtiquetaNombreNuevoClienteVenta = new javax.swing.JLabel();
        jLabelEtiquetaApellidosNuevoClienteVenta = new javax.swing.JLabel();
        jTextFieldDniNuevoClienteVenta = new javax.swing.JTextField();
        jTextFieldNombreNuevoClienteVenta = new javax.swing.JTextField();
        jTextFieldApellidosNuevoClienteVenta = new javax.swing.JTextField();
        jButtonUsarClienteExistente = new javax.swing.JButton();
        jPanelEmpleadoVenta = new javax.swing.JPanel();
        jComboBoxNifEmpleadoVenta = new javax.swing.JComboBox<>();
        jLabelEtiquetaNombreEmpleadoVenta = new javax.swing.JLabel();
        jLabelEtiquetaApellidosEmpleadoVenta = new javax.swing.JLabel();
        jLabelEtiquetaDniEmpleadoVenta = new javax.swing.JLabel();
        jLabelEtiquetaNifEmpleadoVenta = new javax.swing.JLabel();
        jLabelApellidosEmpleadoVenta = new javax.swing.JLabel();
        jLabelNombreEmpleadoVenta = new javax.swing.JLabel();
        jLabelDniEmpleadoVenta = new javax.swing.JLabel();
        jPanelCocheVenta = new javax.swing.JPanel();
        jLabelEtiquetaMarcaCocheVenta = new javax.swing.JLabel();
        jLabelEtiquetaModeloCocheVenta = new javax.swing.JLabel();
        jLabelEtiquetaAnyoCocheVenta = new javax.swing.JLabel();
        jLabelEtiquetaColorCocheVenta = new javax.swing.JLabel();
        jLabelEtiquetaCocheVenta = new javax.swing.JLabel();
        jLabelEtiquetaPrecioCocheVenta = new javax.swing.JLabel();
        jLabelSimboloEuro = new javax.swing.JLabel();
        jLabelMarcaCocheVenta = new javax.swing.JLabel();
        jLabelModeloCocheVenta = new javax.swing.JLabel();
        jLabelAnyoCocheVenta = new javax.swing.JLabel();
        jLabelColorCocheVenta = new javax.swing.JLabel();
        jLabelKilometrajeCocheVenta = new javax.swing.JLabel();
        jLabelPrecioCocheVenta = new javax.swing.JLabel();
        jLabelEtiquetaIdCocheVenta = new javax.swing.JLabel();
        jTextFieldIdCocheConcesionario = new javax.swing.JTextField();
        jButtonMostrarDatosCoche = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jButtonVolverALista = new javax.swing.JButton();
        jButtonRegistrarVenta = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestor Ventas");

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneGestorVentas.setViewportView(jTableVentas);

        jButtonModoRegistrarVenta.setText("Registrar venta -->");
        jButtonModoRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModoRegistrarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListarVentasLayout = new javax.swing.GroupLayout(jPanelListarVentas);
        jPanelListarVentas.setLayout(jPanelListarVentasLayout);
        jPanelListarVentasLayout.setHorizontalGroup(
            jPanelListarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneGestorVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarVentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonModoRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelListarVentasLayout.setVerticalGroup(
            jPanelListarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarVentasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButtonModoRegistrarVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneGestorVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
        );

        jTabbedPaneGestorVentas.addTab("Listar", jPanelListarVentas);

        jPanelClienteVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jComboBoxDniClienteExistente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDniClienteExistenteItemStateChanged(evt);
            }
        });

        jLabelEtiquetaNombreClienteExistente.setText("Nombre: ");

        jLabelEtiquetaApellidosNombreClienteExistente.setText("Apellidos:");

        jLabelEtiquetaDniClienteExistente.setText("DNI:");

        jButtonUsarClienteNuevo.setText("Usar cliente nuevo -->");
        jButtonUsarClienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsarClienteNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteExistenteVentaLayout = new javax.swing.GroupLayout(jPanelClienteExistenteVenta);
        jPanelClienteExistenteVenta.setLayout(jPanelClienteExistenteVentaLayout);
        jPanelClienteExistenteVentaLayout.setHorizontalGroup(
            jPanelClienteExistenteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteExistenteVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteExistenteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteExistenteVentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonUsarClienteNuevo))
                    .addGroup(jPanelClienteExistenteVentaLayout.createSequentialGroup()
                        .addGroup(jPanelClienteExistenteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEtiquetaApellidosNombreClienteExistente)
                            .addComponent(jLabelEtiquetaNombreClienteExistente)
                            .addComponent(jLabelEtiquetaDniClienteExistente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelClienteExistenteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDniClienteExistente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombreClienteExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelApellidosClienteExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jPanelClienteExistenteVentaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelEtiquetaApellidosNombreClienteExistente, jLabelEtiquetaDniClienteExistente, jLabelEtiquetaNombreClienteExistente});

        jPanelClienteExistenteVentaLayout.setVerticalGroup(
            jPanelClienteExistenteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteExistenteVentaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButtonUsarClienteNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteExistenteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaDniClienteExistente)
                    .addComponent(jComboBoxDniClienteExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteExistenteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelEtiquetaNombreClienteExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombreClienteExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelClienteExistenteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaApellidosNombreClienteExistente)
                    .addComponent(jLabelApellidosClienteExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelClienteExistenteVentaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxDniClienteExistente, jLabelApellidosClienteExistente, jLabelEtiquetaApellidosNombreClienteExistente, jLabelEtiquetaDniClienteExistente, jLabelEtiquetaNombreClienteExistente, jLabelNombreClienteExistente});

        jTabbedPaneClienteVenta.addTab("Existente", jPanelClienteExistenteVenta);

        jLabelEtiquetaDniNuevoClienteVenta.setText("DNI:");

        jLabelEtiquetaNombreNuevoClienteVenta.setText("Nombre:");

        jLabelEtiquetaApellidosNuevoClienteVenta.setText("Apellidos:");

        jButtonUsarClienteExistente.setText("<-- Usar cliente existente");
        jButtonUsarClienteExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsarClienteExistenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNuevoClienteVentaLayout = new javax.swing.GroupLayout(jPanelNuevoClienteVenta);
        jPanelNuevoClienteVenta.setLayout(jPanelNuevoClienteVentaLayout);
        jPanelNuevoClienteVentaLayout.setHorizontalGroup(
            jPanelNuevoClienteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoClienteVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNuevoClienteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNuevoClienteVentaLayout.createSequentialGroup()
                        .addComponent(jLabelEtiquetaDniNuevoClienteVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDniNuevoClienteVenta))
                    .addGroup(jPanelNuevoClienteVentaLayout.createSequentialGroup()
                        .addComponent(jLabelEtiquetaApellidosNuevoClienteVenta)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldApellidosNuevoClienteVenta))
                    .addGroup(jPanelNuevoClienteVentaLayout.createSequentialGroup()
                        .addComponent(jLabelEtiquetaNombreNuevoClienteVenta)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldNombreNuevoClienteVenta))
                    .addGroup(jPanelNuevoClienteVentaLayout.createSequentialGroup()
                        .addComponent(jButtonUsarClienteExistente)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelNuevoClienteVentaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelEtiquetaApellidosNuevoClienteVenta, jLabelEtiquetaDniNuevoClienteVenta, jLabelEtiquetaNombreNuevoClienteVenta});

        jPanelNuevoClienteVentaLayout.setVerticalGroup(
            jPanelNuevoClienteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNuevoClienteVentaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButtonUsarClienteExistente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNuevoClienteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaDniNuevoClienteVenta)
                    .addComponent(jTextFieldDniNuevoClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNuevoClienteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaNombreNuevoClienteVenta)
                    .addComponent(jTextFieldNombreNuevoClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNuevoClienteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaApellidosNuevoClienteVenta)
                    .addComponent(jTextFieldApellidosNuevoClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelNuevoClienteVentaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelEtiquetaApellidosNuevoClienteVenta, jLabelEtiquetaDniNuevoClienteVenta, jLabelEtiquetaNombreNuevoClienteVenta});

        jTabbedPaneClienteVenta.addTab("Nuevo", jPanelNuevoClienteVenta);

        javax.swing.GroupLayout jPanelClienteVentaLayout = new javax.swing.GroupLayout(jPanelClienteVenta);
        jPanelClienteVenta.setLayout(jPanelClienteVentaLayout);
        jPanelClienteVentaLayout.setHorizontalGroup(
            jPanelClienteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneClienteVenta)
                .addContainerGap())
        );
        jPanelClienteVentaLayout.setVerticalGroup(
            jPanelClienteVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienteVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneClienteVenta)
                .addContainerGap())
        );

        jPanelEmpleadoVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado"));

        jComboBoxNifEmpleadoVenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNifEmpleadoVentaItemStateChanged(evt);
            }
        });
        jComboBoxNifEmpleadoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNifEmpleadoVentaActionPerformed(evt);
            }
        });

        jLabelEtiquetaNombreEmpleadoVenta.setText("Nombre:");

        jLabelEtiquetaApellidosEmpleadoVenta.setText("Apellidos:");

        jLabelEtiquetaDniEmpleadoVenta.setText("DNI:");

        jLabelEtiquetaNifEmpleadoVenta.setText("NIF:");

        javax.swing.GroupLayout jPanelEmpleadoVentaLayout = new javax.swing.GroupLayout(jPanelEmpleadoVenta);
        jPanelEmpleadoVenta.setLayout(jPanelEmpleadoVentaLayout);
        jPanelEmpleadoVentaLayout.setHorizontalGroup(
            jPanelEmpleadoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmpleadoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEtiquetaDniEmpleadoVenta)
                    .addComponent(jLabelEtiquetaApellidosEmpleadoVenta)
                    .addComponent(jLabelEtiquetaNombreEmpleadoVenta)
                    .addComponent(jLabelEtiquetaNifEmpleadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEmpleadoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxNifEmpleadoVenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelApellidosEmpleadoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNombreEmpleadoVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDniEmpleadoVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelEmpleadoVentaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelEtiquetaApellidosEmpleadoVenta, jLabelEtiquetaDniEmpleadoVenta, jLabelEtiquetaNifEmpleadoVenta, jLabelEtiquetaNombreEmpleadoVenta});

        jPanelEmpleadoVentaLayout.setVerticalGroup(
            jPanelEmpleadoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmpleadoVentaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelEmpleadoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaNifEmpleadoVenta)
                    .addComponent(jComboBoxNifEmpleadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpleadoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEtiquetaNombreEmpleadoVenta)
                    .addComponent(jLabelNombreEmpleadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpleadoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaApellidosEmpleadoVenta)
                    .addComponent(jLabelApellidosEmpleadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEmpleadoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEtiquetaDniEmpleadoVenta)
                    .addComponent(jLabelDniEmpleadoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEmpleadoVentaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxNifEmpleadoVenta, jLabelApellidosEmpleadoVenta, jLabelDniEmpleadoVenta, jLabelEtiquetaApellidosEmpleadoVenta, jLabelEtiquetaDniEmpleadoVenta, jLabelEtiquetaNifEmpleadoVenta, jLabelEtiquetaNombreEmpleadoVenta, jLabelNombreEmpleadoVenta});

        jPanelCocheVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Coche"));

        jLabelEtiquetaMarcaCocheVenta.setText("Marca:");

        jLabelEtiquetaModeloCocheVenta.setText("Modelo:");

        jLabelEtiquetaAnyoCocheVenta.setText("Anyo:");

        jLabelEtiquetaColorCocheVenta.setText("Color:");

        jLabelEtiquetaCocheVenta.setText("Kilometraje:");

        jLabelEtiquetaPrecioCocheVenta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEtiquetaPrecioCocheVenta.setText("Precio:");

        jLabelSimboloEuro.setText("€");

        jLabelPrecioCocheVenta.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabelEtiquetaIdCocheVenta.setText("ID:");

        jButtonMostrarDatosCoche.setText("Mostrar datos");
        jButtonMostrarDatosCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDatosCocheActionPerformed(evt);
            }
        });

        jLabelError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelCocheVentaLayout = new javax.swing.GroupLayout(jPanelCocheVenta);
        jPanelCocheVenta.setLayout(jPanelCocheVentaLayout);
        jPanelCocheVentaLayout.setHorizontalGroup(
            jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCocheVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCocheVentaLayout.createSequentialGroup()
                        .addComponent(jLabelEtiquetaColorCocheVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelColorCocheVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCocheVentaLayout.createSequentialGroup()
                        .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCocheVentaLayout.createSequentialGroup()
                                .addComponent(jLabelEtiquetaIdCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldIdCocheConcesionario))
                            .addGroup(jPanelCocheVentaLayout.createSequentialGroup()
                                .addComponent(jLabelEtiquetaMarcaCocheVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelMarcaCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelEtiquetaModeloCocheVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelModeloCocheVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelEtiquetaAnyoCocheVenta)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAnyoCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMostrarDatosCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCocheVentaLayout.createSequentialGroup()
                        .addComponent(jLabelEtiquetaCocheVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKilometrajeCocheVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEtiquetaPrecioCocheVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPrecioCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSimboloEuro))
                    .addComponent(jLabelError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCocheVentaLayout.setVerticalGroup(
            jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCocheVentaLayout.createSequentialGroup()
                .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaIdCocheVenta)
                    .addComponent(jTextFieldIdCocheConcesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrarDatosCoche))
                .addGap(18, 18, 18)
                .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEtiquetaMarcaCocheVenta)
                        .addComponent(jLabelEtiquetaModeloCocheVenta)
                        .addComponent(jLabelEtiquetaAnyoCocheVenta)
                        .addComponent(jLabelModeloCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAnyoCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelMarcaCocheVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaColorCocheVenta)
                    .addComponent(jLabelColorCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEtiquetaPrecioCocheVenta)
                        .addComponent(jLabelSimboloEuro)
                        .addComponent(jLabelPrecioCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCocheVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelEtiquetaCocheVenta)
                        .addComponent(jLabelKilometrajeCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        jButtonVolverALista.setText("<-- Volver a listado");
        jButtonVolverALista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverAListaActionPerformed(evt);
            }
        });

        jButtonRegistrarVenta.setBackground(new java.awt.Color(0, 153, 255));
        jButtonRegistrarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegistrarVenta.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrarVenta.setText("Registrar venta");
        jButtonRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrarVentasLayout = new javax.swing.GroupLayout(jPanelRegistrarVentas);
        jPanelRegistrarVentas.setLayout(jPanelRegistrarVentasLayout);
        jPanelRegistrarVentasLayout.setHorizontalGroup(
            jPanelRegistrarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistrarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCocheVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRegistrarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistrarVentasLayout.createSequentialGroup()
                        .addComponent(jButtonVolverALista, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistrarVentasLayout.createSequentialGroup()
                        .addComponent(jPanelEmpleadoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelClienteVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRegistrarVentasLayout.setVerticalGroup(
            jPanelRegistrarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolverALista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrarVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEmpleadoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelClienteVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCocheVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneGestorVentas.addTab("Anyadir", jPanelRegistrarVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneGestorVentas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGestorVentas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModoRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModoRegistrarVentaActionPerformed
        ModoRegistrarVenta();
    }//GEN-LAST:event_jButtonModoRegistrarVentaActionPerformed

    private void jButtonVolverAListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverAListaActionPerformed
        VolverALista();
    }//GEN-LAST:event_jButtonVolverAListaActionPerformed

    private void jButtonUsarClienteExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsarClienteExistenteActionPerformed
        UsarClienteExistente();
    }//GEN-LAST:event_jButtonUsarClienteExistenteActionPerformed

    private void jComboBoxNifEmpleadoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNifEmpleadoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNifEmpleadoVentaActionPerformed

    private void jComboBoxNifEmpleadoVentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNifEmpleadoVentaItemStateChanged
        String nif = String.valueOf(jComboBoxNifEmpleadoVenta.getSelectedItem());
        IniciarDatosEmpleado(nif);
    }//GEN-LAST:event_jComboBoxNifEmpleadoVentaItemStateChanged

    private void jButtonRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarVentaActionPerformed
        String nif_empleado;
        String dni_cliente;
        long id_coche;
        String fecha;
        
        nif_empleado = String.valueOf(jComboBoxNifEmpleadoVenta.getSelectedItem());
        
        if (nuevoCliente == true) {
            dni_cliente = jTextFieldDniNuevoClienteVenta.getText();
            String nombre = jTextFieldNombreNuevoClienteVenta.getText();
            String apellidos = jTextFieldApellidosNuevoClienteVenta.getText();
            c.RegistrarCliente(dni_cliente, nombre, apellidos);
            
            dni_cliente = jTextFieldDniNuevoClienteVenta.getText();
        } else {
            dni_cliente = String.valueOf(jComboBoxDniClienteExistente.getSelectedItem());
        }
        
        id_coche = Long.parseLong(jTextFieldIdCocheConcesionario.getText());
        fecha = c.ObtenerFechaActual();
        
        c.CambiarDisponibilidadAVendido(id_coche);
        c.RegistrarVenta(nif_empleado, dni_cliente, id_coche, fecha);
        
        IniciarTablaVentas();
        c.CargarTablaVentas(dtm);
        
        jTextFieldIdCocheConcesionario.setText("");
        jLabelMarcaCocheVenta.setText("");
        jLabelModeloCocheVenta.setText("");
        jLabelAnyoCocheVenta.setText("");
        jLabelColorCocheVenta.setText("");
        jLabelKilometrajeCocheVenta.setText("");
        jLabelPrecioCocheVenta.setText("");
        
        UsarClienteExistente();
        VolverALista();
        
    }//GEN-LAST:event_jButtonRegistrarVentaActionPerformed

    private void jButtonMostrarDatosCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDatosCocheActionPerformed
        String id_String = jTextFieldIdCocheConcesionario.getText();
        long id = 0;

        if (id_String.length() > 0) {
            id = Long.parseLong(id_String);
            IniciarDatosCoche(id);
        } else {
            jLabelError.setText("El campo 'ID' esta vacio.");
        }
    }//GEN-LAST:event_jButtonMostrarDatosCocheActionPerformed

    private void jButtonUsarClienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsarClienteNuevoActionPerformed
        UsarClienteNuevo();
    }//GEN-LAST:event_jButtonUsarClienteNuevoActionPerformed

    private void jComboBoxDniClienteExistenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDniClienteExistenteItemStateChanged
        String dni = String.valueOf(jComboBoxDniClienteExistente.getSelectedItem());
        IniciarDatosCliente(dni);
    }//GEN-LAST:event_jComboBoxDniClienteExistenteItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModoRegistrarVenta;
    private javax.swing.JButton jButtonMostrarDatosCoche;
    private javax.swing.JButton jButtonRegistrarVenta;
    private javax.swing.JButton jButtonUsarClienteExistente;
    private javax.swing.JButton jButtonUsarClienteNuevo;
    private javax.swing.JButton jButtonVolverALista;
    private javax.swing.JComboBox<String> jComboBoxDniClienteExistente;
    private javax.swing.JComboBox<String> jComboBoxNifEmpleadoVenta;
    private javax.swing.JLabel jLabelAnyoCocheVenta;
    private javax.swing.JLabel jLabelApellidosClienteExistente;
    private javax.swing.JLabel jLabelApellidosEmpleadoVenta;
    private javax.swing.JLabel jLabelColorCocheVenta;
    private javax.swing.JLabel jLabelDniEmpleadoVenta;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelEtiquetaAnyoCocheVenta;
    private javax.swing.JLabel jLabelEtiquetaApellidosEmpleadoVenta;
    private javax.swing.JLabel jLabelEtiquetaApellidosNombreClienteExistente;
    private javax.swing.JLabel jLabelEtiquetaApellidosNuevoClienteVenta;
    private javax.swing.JLabel jLabelEtiquetaCocheVenta;
    private javax.swing.JLabel jLabelEtiquetaColorCocheVenta;
    private javax.swing.JLabel jLabelEtiquetaDniClienteExistente;
    private javax.swing.JLabel jLabelEtiquetaDniEmpleadoVenta;
    private javax.swing.JLabel jLabelEtiquetaDniNuevoClienteVenta;
    private javax.swing.JLabel jLabelEtiquetaIdCocheVenta;
    private javax.swing.JLabel jLabelEtiquetaMarcaCocheVenta;
    private javax.swing.JLabel jLabelEtiquetaModeloCocheVenta;
    private javax.swing.JLabel jLabelEtiquetaNifEmpleadoVenta;
    private javax.swing.JLabel jLabelEtiquetaNombreClienteExistente;
    private javax.swing.JLabel jLabelEtiquetaNombreEmpleadoVenta;
    private javax.swing.JLabel jLabelEtiquetaNombreNuevoClienteVenta;
    private javax.swing.JLabel jLabelEtiquetaPrecioCocheVenta;
    private javax.swing.JLabel jLabelKilometrajeCocheVenta;
    private javax.swing.JLabel jLabelMarcaCocheVenta;
    private javax.swing.JLabel jLabelModeloCocheVenta;
    private javax.swing.JLabel jLabelNombreClienteExistente;
    private javax.swing.JLabel jLabelNombreEmpleadoVenta;
    private javax.swing.JLabel jLabelPrecioCocheVenta;
    private javax.swing.JLabel jLabelSimboloEuro;
    private javax.swing.JPanel jPanelClienteExistenteVenta;
    private javax.swing.JPanel jPanelClienteVenta;
    private javax.swing.JPanel jPanelCocheVenta;
    private javax.swing.JPanel jPanelEmpleadoVenta;
    private javax.swing.JPanel jPanelListarVentas;
    private javax.swing.JPanel jPanelNuevoClienteVenta;
    private javax.swing.JPanel jPanelRegistrarVentas;
    private javax.swing.JScrollPane jScrollPaneGestorVentas;
    private javax.swing.JTabbedPane jTabbedPaneClienteVenta;
    private javax.swing.JTabbedPane jTabbedPaneGestorVentas;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTextField jTextFieldApellidosNuevoClienteVenta;
    private javax.swing.JTextField jTextFieldDniNuevoClienteVenta;
    private javax.swing.JTextField jTextFieldIdCocheConcesionario;
    private javax.swing.JTextField jTextFieldNombreNuevoClienteVenta;
    // End of variables declaration//GEN-END:variables
}
