/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;

/**
 *
 * @author paugi
 */
public class InicioSesion extends javax.swing.JInternalFrame {
    
    Controlador c;
    JMenuBar jMenuBarGestion;
    JDesktopPane jDesktopPaneEscritorio;
    JMenu jMenuClientes;
    JMenu jMenuCoches;
    JMenu jMenuCompras;
    JMenu jMenuEmpleados;
    JMenu jMenuOpciones;
    JMenu jMenuVentas;
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion(Controlador c, JMenuBar jMenuBarGestion, JDesktopPane jDesktopPaneEscritorio, JMenu jMenuClientes, JMenu jMenuCoches, JMenu jMenuCompras, JMenu jMenuEmpleados, JMenu jMenuOpciones, JMenu jMenuVentas) {
        initComponents();
        this.c = c;
        this.jMenuBarGestion = jMenuBarGestion;
        this.jDesktopPaneEscritorio = jDesktopPaneEscritorio;
        this.jMenuClientes = jMenuClientes;
        this.jMenuCoches = jMenuCoches;
        this.jMenuCompras = jMenuCompras;
        this.jMenuEmpleados = jMenuEmpleados;
        this.jMenuOpciones = jMenuOpciones;
        this.jMenuVentas = jMenuVentas;
        
        
        jMenuBarGestion.setEnabled(false);
        jDesktopPaneEscritorio.setEnabled(false);
        jMenuClientes.setEnabled(false);
        jMenuCoches.setEnabled(false);
        jMenuCompras.setEnabled(false);
        jMenuEmpleados.setEnabled(false);
        jMenuOpciones.setEnabled(false);
        jMenuVentas.setEnabled(false);
    }
    
    private boolean VerificarInicioSesion() {
        String nom_usuario = jTextFieldNombreUsuario.getText();
        char[] cadenaContrasenya = jPasswordFieldContrasenya.getPassword();
        String contrasenya = String.valueOf(cadenaContrasenya);
        boolean verificacion = c.VerificarInicioSesion(nom_usuario, contrasenya);
        
        return verificacion;
    }
    
    private boolean RegistrarUsuario() {
        String nom_usuario = jTextFieldNombreUsuario.getText();
        char[] cadenaContrasenya = jPasswordFieldContrasenya.getPassword();
        String contrasenya = String.valueOf(cadenaContrasenya);
        boolean verificacion = c.RegistrarUsuario(nom_usuario, contrasenya);
        
        return verificacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombreUsuario = new javax.swing.JTextField();
        jButtonInicioSesion = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jLabelO = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();
        jPasswordFieldContrasenya = new javax.swing.JPasswordField();

        setTitle("Inicio sesion");

        jTextFieldNombreUsuario.setToolTipText("Nombre de usuario");
        jTextFieldNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUsuarioActionPerformed(evt);
            }
        });

        jButtonInicioSesion.setText("Inicia sesion");
        jButtonInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioSesionActionPerformed(evt);
            }
        });

        jButtonRegistrar.setText("Registrate");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabelO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelO.setText("o");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Inicio Sesión");

        jLabelError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldContrasenya)
                    .addComponent(jTextFieldNombreUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelO, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordFieldContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicioSesion)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jLabelO))
                .addGap(18, 18, 18)
                .addComponent(jLabelError, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jTextFieldNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUsuarioActionPerformed
        
    }//GEN-LAST:event_jTextFieldNombreUsuarioActionPerformed

    private void jButtonInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioSesionActionPerformed
        boolean verificacion = VerificarInicioSesion();
        if (verificacion == true) {
            jMenuBarGestion.setEnabled(true);
            jDesktopPaneEscritorio.setEnabled(true);
            jMenuClientes.setEnabled(true);
            jMenuCoches.setEnabled(true);
            jMenuCompras.setEnabled(true);
            jMenuEmpleados.setEnabled(true);
            jMenuOpciones.setEnabled(true);
            jMenuVentas.setEnabled(true);
            this.setVisible(false);
        } else {
            jLabelError.setText("El nombre de usuario o contrasenya no es el correcto.");
            jTextFieldNombreUsuario.setText("");
            jPasswordFieldContrasenya.setText("");
        }
        
        
    }//GEN-LAST:event_jButtonInicioSesionActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        boolean verificacion = RegistrarUsuario();
        
        if (verificacion == true) {
            jTextFieldNombreUsuario.setText("");
            jPasswordFieldContrasenya.setText("");
            jLabelError.setText("");
        } else {
            jLabelError.setText("Es posible que ese usuario ya exista o hayas dejado algun campo en blanco.");
            jTextFieldNombreUsuario.setText("");
            jPasswordFieldContrasenya.setText("");
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInicioSesion;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelO;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPasswordFieldContrasenya;
    private javax.swing.JTextField jTextFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
