/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import java.awt.Dimension;
import static java.lang.System.exit;

/**
 *
 * @author paugi
 */
public class MenuPrincipal extends javax.swing.JFrame {
    Controlador c;
    InicioSesion inicioSesion;
    GestorClientes gestorClientes;
    GestorCoches gestorCoches;
    GestorCompras gestorCompras;
    GestorEmpleados gestorEmpleados;
    GestorVentas gestorVentas;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        c = new Controlador();       
        gestorClientes = new GestorClientes(c);
        gestorCoches = new GestorCoches(c);
        gestorCompras = new GestorCompras(c, 0);
        gestorEmpleados = new GestorEmpleados(c, 0);
        gestorVentas = new GestorVentas(c, 0);
        
        inicioSesion = new InicioSesion(c, jMenuBarGestion, jDesktopPaneEscritorio, jMenuClientes, jMenuCoches, jMenuCompras, jMenuEmpleados, jMenuOpciones, jMenuVentas);    
        CentrarVentanaInicioSesion();
        
        jDesktopPaneEscritorio.add(inicioSesion);
        inicioSesion.setVisible(true);
    }
    
    private void CentrarVentanaInicioSesion() {
        Dimension tamanyoEscritorio = jDesktopPaneEscritorio.getSize();
        Dimension tamanyoInicioSesion = inicioSesion.getSize();
        
        inicioSesion.setLocation((tamanyoEscritorio.width - tamanyoInicioSesion.width)/2, (tamanyoEscritorio.height- tamanyoInicioSesion.height)/2);
    }
    
    private void CerrarVentanas() {
        gestorClientes.setVisible(false);
        gestorCoches.setVisible(false);
        gestorCompras.setVisible(false);
        gestorEmpleados.setVisible(false);
        gestorVentas.setVisible(false);
        inicioSesion = new InicioSesion(c, jMenuBarGestion, jDesktopPaneEscritorio, jMenuClientes, jMenuCoches, jMenuCompras, jMenuEmpleados, jMenuOpciones, jMenuVentas);    
        CentrarVentanaInicioSesion();
        
        jDesktopPaneEscritorio.add(inicioSesion);
        inicioSesion.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneEscritorio = new javax.swing.JDesktopPane();
        jMenuBarGestion = new javax.swing.JMenuBar();
        jMenuVentas = new javax.swing.JMenu();
        jMenuItemListarVentas = new javax.swing.JMenuItem();
        jMenuItemRegistrarVenta = new javax.swing.JMenuItem();
        jMenuCompras = new javax.swing.JMenu();
        jMenuItemListarCompras = new javax.swing.JMenuItem();
        jMenuItemRegistrarCompra = new javax.swing.JMenuItem();
        jMenuEmpleados = new javax.swing.JMenu();
        jMenuItemListarEmpleados = new javax.swing.JMenuItem();
        jMenuItemRegistrarEmpleado = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemListarClientes = new javax.swing.JMenuItem();
        jMenuCoches = new javax.swing.JMenu();
        jMenuItemListarCoches = new javax.swing.JMenuItem();
        jMenuOpciones = new javax.swing.JMenu();
        jMenuItemCambiarUsuario = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneEscritorioLayout = new javax.swing.GroupLayout(jDesktopPaneEscritorio);
        jDesktopPaneEscritorio.setLayout(jDesktopPaneEscritorioLayout);
        jDesktopPaneEscritorioLayout.setHorizontalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1272, Short.MAX_VALUE)
        );
        jDesktopPaneEscritorioLayout.setVerticalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );

        jMenuBarGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuVentas.setText("Ventas");

        jMenuItemListarVentas.setText("Listar");
        jMenuItemListarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarVentasActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemListarVentas);

        jMenuItemRegistrarVenta.setText("Registrar Venta");
        jMenuItemRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarVentaActionPerformed(evt);
            }
        });
        jMenuVentas.add(jMenuItemRegistrarVenta);

        jMenuBarGestion.add(jMenuVentas);

        jMenuCompras.setText("Compras");

        jMenuItemListarCompras.setText("Listar");
        jMenuItemListarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarComprasActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuItemListarCompras);

        jMenuItemRegistrarCompra.setText("Registrar Compra");
        jMenuItemRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarCompraActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuItemRegistrarCompra);

        jMenuBarGestion.add(jMenuCompras);

        jMenuEmpleados.setText("Empleados");

        jMenuItemListarEmpleados.setText("Listar");
        jMenuItemListarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarEmpleadosActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemListarEmpleados);

        jMenuItemRegistrarEmpleado.setText("Registrar nuevo empleado");
        jMenuItemRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemRegistrarEmpleado);

        jMenuBarGestion.add(jMenuEmpleados);

        jMenuClientes.setText("Clientes");

        jMenuItemListarClientes.setText("Listar");
        jMenuItemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemListarClientes);

        jMenuBarGestion.add(jMenuClientes);

        jMenuCoches.setText("Coches");

        jMenuItemListarCoches.setText("Listar");
        jMenuItemListarCoches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarCochesActionPerformed(evt);
            }
        });
        jMenuCoches.add(jMenuItemListarCoches);

        jMenuBarGestion.add(jMenuCoches);

        jMenuOpciones.setText("Opciones");

        jMenuItemCambiarUsuario.setText("Cambiar de usuario");
        jMenuItemCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarUsuarioActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemCambiarUsuario);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuOpciones.add(jMenuItemSalir);

        jMenuBarGestion.add(jMenuOpciones);

        setJMenuBar(jMenuBarGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemListarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarVentasActionPerformed
        if (!gestorVentas.isVisible()) {
            gestorVentas = new GestorVentas(c, 0);
            jDesktopPaneEscritorio.add(gestorVentas);
            gestorVentas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemListarVentasActionPerformed

    private void jMenuItemListarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarComprasActionPerformed
        if (!gestorCompras.isVisible()) {
            gestorCompras = new GestorCompras(c, 0);
            jDesktopPaneEscritorio.add(gestorCompras);
            gestorCompras.setVisible(true);
        }        
    }//GEN-LAST:event_jMenuItemListarComprasActionPerformed

    private void jMenuItemListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarEmpleadosActionPerformed
        if (!gestorEmpleados.isVisible()) {
            gestorEmpleados = new GestorEmpleados(c, 0);
            jDesktopPaneEscritorio.add(gestorEmpleados);
            gestorEmpleados.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemListarEmpleadosActionPerformed

    private void jMenuItemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarClientesActionPerformed
        if (!gestorClientes.isVisible()) {
            gestorClientes = new GestorClientes(c);
            jDesktopPaneEscritorio.add(gestorClientes);
            gestorClientes.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemListarClientesActionPerformed

    private void jMenuItemListarCochesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarCochesActionPerformed
        if (!gestorCoches.isVisible()) {
            gestorCoches = new GestorCoches(c);
            jDesktopPaneEscritorio.add(gestorCoches);
            gestorCoches.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemListarCochesActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarCompraActionPerformed
        if (!gestorCompras.isVisible()) {
            gestorCompras = new GestorCompras(c, 1);
            jDesktopPaneEscritorio.add(gestorCompras);
            gestorCompras.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemRegistrarCompraActionPerformed

    private void jMenuItemRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarEmpleadoActionPerformed
        if (!gestorEmpleados.isVisible()) {
            gestorEmpleados = new GestorEmpleados(c, 1);
            jDesktopPaneEscritorio.add(gestorEmpleados);
            gestorEmpleados.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemRegistrarEmpleadoActionPerformed

    private void jMenuItemRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarVentaActionPerformed
        if (!gestorVentas.isVisible()) {
            gestorVentas = new GestorVentas(c, 1);
            jDesktopPaneEscritorio.add(gestorVentas);
            gestorVentas.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItemRegistrarVentaActionPerformed

    private void jMenuItemCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarUsuarioActionPerformed
        CerrarVentanas();
    }//GEN-LAST:event_jMenuItemCambiarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneEscritorio;
    private javax.swing.JMenuBar jMenuBarGestion;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuCoches;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenu jMenuEmpleados;
    private javax.swing.JMenuItem jMenuItemCambiarUsuario;
    private javax.swing.JMenuItem jMenuItemListarClientes;
    private javax.swing.JMenuItem jMenuItemListarCoches;
    private javax.swing.JMenuItem jMenuItemListarCompras;
    private javax.swing.JMenuItem jMenuItemListarEmpleados;
    private javax.swing.JMenuItem jMenuItemListarVentas;
    private javax.swing.JMenuItem jMenuItemRegistrarCompra;
    private javax.swing.JMenuItem jMenuItemRegistrarEmpleado;
    private javax.swing.JMenuItem jMenuItemRegistrarVenta;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuOpciones;
    private javax.swing.JMenu jMenuVentas;
    // End of variables declaration//GEN-END:variables
}
